### ISSUE TITLE
CrazyAuctions error when selling an item with a unique name

### ISSUE THREAD

**Issue by Medic4903** [badbones69/Crazy-Auctions#82] opened 2019-09-19 09:51 UTC
Spigot: 1.14.4
Crazy-Auctions: v1.12.10

Log:
https://pastebin.com/M7yh8LTA

**Comment by badbones69** [comment] 2019-09-19 09:55
It is an issue with CrazyAuctionsAnnouncer, not CrazyAuctions. Seems based on the Discord for that plugin the issue is known and has been fixed and will be in the next update of the plugin.

**Closed by badbones69** 2019-09-19 09:55 UTC
